input_path: data/ingested
output_path: data/preprocessed
output_array_size: 64
font_extraction_config:
  font_extraction_size: 100
  canvas_size: 500
  canvas_padding: 100
beam_cmd_line_args:
-  --runner
-  DirectRunner
- --direct_num_workers
- 6
