output_path: data/ingested
max_zip_size: 128 #max size in MB 
scrappers: #list of StreamRetriever instances that will be used to produce scrappable URLs
- class: LocalFileScrapper
  kwargs: 
    path: data/font-zipfiles/google
- class: LocalFileScrapper
  kwargs: 
    path: data/font-zipfiles/dafont
- class: LocalFileScrapper
  kwargs: 
    path: data/font-zipfiles/1001free
