# Train a generative model based on the adversarial autoencoder architecture by Goodfellow et al. 
input_path: data/uppercase-scored
input_record_class: ScoredLabeledChar
output_path: data/uppercase-embeddings
model_path: models/generative-uppercase
charset: uppercase
training:
  filters:
  - name: filter_misclassified
  - name: filter_score
    kwargs:
      threshold: 0.95
  batch_size: 64
  epochs: 30
  steps_per_epoch: 5000
  optimizer:
    class: Adam
    kwargs:
      learning_rate: 0.001
  loss:
    class: CategoricalCrossentropy
  metrics:
  - accuracy
  callbacks:
  - class: TensorBoard
    kwargs:
      log_dir: logs/tensorboard/supervised-uppercase
  - class: ModelCheckpoint
    kwargs:
      filepath: models/generative-uppercase-checkpoint
      monitor: MSE
model:
  class: CharStyleSAAE
  kwargs:
    prior_batch_size: 64
    reconstruction_loss_weight: 0.5
    discriminator:
      class: Sequential
      kwargs:
        layers:
        - class: Input
          kwargs:
            shape:
            - 10
        - class: Dense
          kwargs:
            units: 100
            activation: elu
        - class: Dense
          kwargs:
            units: 100
            activation: elu
        - class: Dense
          kwargs:
            units: 1
            activation: sigmoid
    image_encoder:
      class: Sequential
      kwargs:
        layers:
        - class: Input
          kwargs:
            shape:
            - 64
            - 64
            - 1
        - class: Conv2D
          kwargs: 
            filters: 64
            kernel_size: 3
            activation: elu
            padding: same
        - class: MaxPooling2D
          kwargs:
            pool_size: 2
        - class: BatchNormalization
        - class: Conv2D
          kwargs: 
            filters: 96
            kernel_size: 3
            activation: elu
            padding: same
        - class: MaxPooling2D
          kwargs: 
            pool_size: 2
        - class: BatchNormalization
        - class: Conv2D
          kwargs: 
            filters: 64
            kernel_size: 3
            activation: elu
            padding: same
        - class: MaxPooling2D
          kwargs: 
            pool_size: 2
        - class: BatchNormalization
        - class: Conv2D
          kwargs: 
            filters: 64
            kernel_size: 3
            activation: elu
            padding: same
        - class: MaxPooling2D
          kwargs: 
            pool_size: 2
        - class: BatchNormalization
        - class: Flatten
    full_encoder:
      class: Sequential
      kwargs:
        layers:
        - class: Input
          kwargs:
            shape: 
            - 1050
        - class: Dense
          kwargs:
            units: 1024
            activation: elu
        - class: Dense
          kwargs:
            units: 1024
            activation: elu
        - class: Dense
          kwargs:
            units: 10
    decoder:
      class: Sequential
      kwargs:
        layers:
        - class: Input
          kwargs:
            shape:
            - 36
        - class: Dense
          kwargs: 
            units: 1024
            activation: elu
        - class: Dense
          kwargs: 
            units: 1024
            activation: elu
        - class: Reshape
          kwargs: 
            target_shape: 
            - 4
            - 4
            - 64
        - class: Conv2DTranspose
          kwargs:
            kernel_size: 2
            activation: elu
            strides: 2
            filters: 64
        - class: Conv2D
          kwargs: 
            filters: 96
            kernel_size: 3
            activation: elu
            padding: same
        - class: BatchNormalization
        - class: Conv2DTranspose
          kwargs:
            kernel_size: 2
            activation: elu
            strides: 2
            filters: 64
        - class: Conv2D
          kwargs: 
            filters: 32
            kernel_size: 3
            activation: elu
            padding: same
        - class: BatchNormalization
        - class: Conv2DTranspose
          kwargs:
            kernel_size: 2
            activation: elu
            strides: 2
            filters: 32
        - class: Conv2D
          kwargs: 
            filters: 1
            kernel_size: 3
            activation: elu
            padding: same
        - class: BatchNormalization
        - class: Conv2DTranspose
          kwargs:
            kernel_size: 2
            activation: elu
            strides: 2
            filters: 32
        - class: Conv2D
          kwargs: 
            filters: 1
            kernel_size: 3
            activation: sigmoid
            padding: same
