# Train a generative model based on the adversarial autoencoder architecture by Goodfellow et al. 
input_path: data/scored/uppercase/fonts
input_record_class: ScoredLabeledFont
output_path: data/scored/uppercase/font-style-gen
model_path: models/font-style-generative
charset: uppercase
training:
  custom_mappers:
  - name: drop_misclassified_in_font
  custom_filters:
  - name: filter_fonts_by_size
    kwargs:
      n_chars: 24
  epochs: 30
  steps_per_epoch: 5000
  optimizer:
    class: Adam
    kwargs:
      learning_rate: 0.001
  loss:
    class: CategoricalCrossentropy
  metrics:
  - accuracy
  callbacks:
  - class: SAAEFontSamplerCallback
    kwargs:
      n_labels: 26
      embedding_dim: 10
  - class: SAAELRHalver
    kwargs:
      halve_after: 12
model:
  custom_class: PureFontStyleSAAE
  path: models/font-style-generative