scrappers:
- class: LocalScrapper
  kwargs: 
    folder: /font-zipfiles/1001free
- class: LocalScrapper
  kwargs: 
    folder: /font-zipfiles/dafont
- class: LocalScrapper
  kwargs: 
    folder: /font-zipfiles/google
output_path: data/raw


