input_path: data/preprocessed
output_path: data/scored
model_path: data/model
training:
  batch_size: 64
  epochs: 10 
  steps_per_epoch: 125000
  optimizer:
    class: Adam
  loss:
    class: CategoricalCrossentropy
  metrics:
  - accuracy
model:
  class: SAAE
  kwargs:
    encoder:
    - class: Conv2D
      kwargs: 
        filters: 32
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs:
        pool_size: 2
    - class: BatchNormalization
    - class: Conv2D
      kwargs: 
        filters: 96
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 128
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs: 
        pool_size: 2
    - class: BatchNormalization
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs: 
        pool_size: 2
    - class: BatchNormalization
    - class: Flatten
    - class: Dropout
      kwargs: 
        rate: 0.5
    - class: Dense
      kwargs:
        units: 26
    decoder:
    - class: Conv2D
      kwargs: 
        filters: 32
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs:
        pool_size: 2
    - class: BatchNormalization
    - class: Conv2D
      kwargs: 
        filters: 96
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 128
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs: 
        pool_size: 2
    - class: BatchNormalization
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: Conv2D
      kwargs: 
        filters: 64
        kernel_size: 3
        activation: elu
        padding: same
    - class: MaxPooling2D
      kwargs: 
        pool_size: 2
    - class: BatchNormalization
    - class: Flatten
    - class: Dropout
      kwargs: 
        rate: 0.5
    - class: Dense
      kwargs:
        units: 26
