input_path: data/ingested
reader: ZipReader
output_path: data/preprocessed
writer: TfrWriter
output_array_size: 64
font_extraction_size: 100
canvas_size: 500
canvas_padding: 100
beam_cmd_line_args:
-  --runner
-  DirectRunner
- --direct_num_workers
- 6
