input_path: data/uppercase-scored
output_path: data/uppercase-embeddings
model_path: models/generative-uppercase
charset: uppercase
training:
  filters:
  - name: filter_misclassified
  - name: filter_score
    kwargs:
      threshold: 0.95
  batch_size: 128
  epochs: 25
  steps_per_epoch: 5000
  optimizer:
    class: Adam
    kwargs:
      learning_rate: 0.0005
  loss:
    class: CategoricalCrossentropy
  metrics:
  - accuracy
  callbacks:
  - class: TensorBoard
    kwargs:
      log_dir: logs/tensorboard/supervised-uppercase
  - class: ModelCheckpoint
    kwargs:
      filepath: models/generative-uppercase-checkpoint
      monitor: MSE
model:
  path: models/generative-uppercase
  custom_class: SAAE