# This config does not orders the ouput images in any particular way
output_record_class: LabeledChar
input_path: data/google/raw
output_path: data/google/preprocessed/chars
output_array_size: 64
max_output_file_size: 64 #in MB
font_extraction_size: 100
canvas_size: 500
canvas_padding: 100
beam_cmd_line_args:
-  --runner
-  DirectRunner
- --direct_num_workers
- 1 #its a single, huge zip, so there's no point in running it in parallel
- --direct_running_mode
- multi_processing